title: Silbele Cosmetics
author:
  name: Silbele Team
  email: 'hello@silbele.com'
metadata:
    description: 'Premium cosmetics and skincare products. Your beauty, redefined with Silbele Cosmetics.'
taxonomies:
    category: blog
    tag: blog
blog:
    route: /blog

